### ISSUE TITLE
Support one pile per git worktree

### ISSUE THREAD

**Issue by ashutoshx** [git-pile/git-pile#110]
We already have use cases with multiple worktrees within a single repo and we would like to have a pile in each such worktree. Appears this is not currently supported. Currently (v1.1) the last pile created becomes the only pile and overwrites the previous pile in a different worktree. .git/config only shows a single pile, the last one created.

Creating this issue to support one pile per worktree, so that git pile commands (reset, format-patch, genbranch) can be run from multiple worktrees transparently.

**Comment by lucasdemarchi** [comment]
It's already supported since 1.0 with several bug fixes in 1.1. The key is for that to work you have to enable the per worktree git extension

**Comment by ashutoshx** [comment]
Thanks @lucasdemarchi, will try this out, it wasn't clear this was needed.

**Comment by lucasdemarchi** [comment]
To be clear, this is the configuration needed: `git config --local extensions.worktreeConfig true`
From 1.0 release notes (https://github.com/git-pile/git-pile/releases/tag/v1.0): "Support worktree-aware pile branches. Now git-pile works with extensions.worktreeConfig to allow setting up multiple pairs of result-branch/pile-branch in a single repository."
