### ISSUE TITLE
[BUG]Pile parsing failed, if any line in the description starts with word "From"

### ISSUE THREAD

**Issue by piotrpiorkow** [git-pile/git-pile#19]
I have encountered a situation where executing the git pile am ~ /path/to/pile command ends with the message:
 "error: Patch doesn't look like a git-pile cover letter: failed to find version information"

The pile file was generated by a git-pile (in the same version) and was not modified (except for the mail client)

The problem was that the pile file contained a description where one of the lines started with the word "From"
After removing that word, everything started working.

**Comment by zehortigoza** [comment]
Could you attach the generated pile with the description?

**Comment by piotrpiorkow** [comment]
That pile was confidential. I will try to prepare some other pile that causes an error.

**Comment by piotrpiorkow** [comment]
[test.zip](https://github.com/git-pile/git-pile/files/5972298/test.zip)
[0000-cover-letter.zip](https://github.com/git-pile/git-pile/files/5972322/0000-cover-letter.zip)

I attached minimal git repo and pile files causing the problem.

**Comment by lucasdemarchi** [comment]
It looks like a bug in python's mailbox module:

```py
>>> import mailbox
>>> mbox = mailbox.mbox('0000-cover-letter.patch')
>>> len(mbox)
2
>>> mbox[0].get_from()
'0000000000000000000000000000000000000000 Mon Sep 17 00:00:00 2001'
>>> mbox[1].get_from()
'somewhere'
```

**Comment by lucasdemarchi** [comment]
Even if we remove the check, we'd still hit this bug: the reason we use a mbox there is that patchwork allows you to download the complete patch series with cover or without cover, but doesn't allow you to download just the cover. So we have to split the mbox into the corresponding emails so we can extract the first one as the cover letter.

**Comment by lucasdemarchi** [comment]
Ohh... looking at https://patchwork.freedesktop.org/, it seems now there are links for 1) patches; 2) cover; 3) patches + cover. So we may change git-pile to always use just 1 email in the mbox rather than possibly split it.
