### ISSUE TITLE
Teach format-patch to add only new patches

### ISSUE THREAD

**Issue by lucasdemarchi** [git-pile/git-pile#25]
Sometimes it's good to have a way to tell git-pile format-patch to include only the new patches as "standalone emails". The interdiff and overall diff is already sent so there is no information lost. This is particularly important when adding a patch to the bottom of a branch creates a bunch of conflicts and ends up touch hundreds of patches.

It may be just a command line option, or we could use a (configurable) threshold with number of patches changed.

**Comment by lucasdemarchi** [comment]
@mattrope @ashutoshx  thoughts? I want to start marking the issues that are important for the next version, and I'm thinking this is one of them.

**Comment by mattrope** [comment]
Yeah, this makes sense to me.  The only time I ever look at the individual patch emails instead of the cover letter or interdiff is when I want to leave a per-patch r-b or something.  And that only happens on brand new patches, since otherwise I just ack the deltas in the cover letter.

**Comment by lucasdemarchi** [comment]
Thinking about trying this unconditionally, just changing the default behavior, and trying for some days

**Comment by ashutoshx** [comment]
Yes, let's make it the default and try it and see if anyone complains. I'm with @mattrope, I never look at the other patches, just the cover letter and the full tree diff. Could probably do issue #26 too in the same iteration?

**Comment by lucasdemarchi** [comment]
Yeah... I did that yesterday. Just waiting to complete a patch series so I can try it in a real world scenario. I will submit a PR soon.

**Comment by ashutoshx** [comment]
When the baseline changes (in the form 'git pile format-patch OLD_BASELINE..OLD_RESULT_HEAD NEW_BASELINE..NEW_RESULT_HEAD'), git pile doesn't generate a full tree diff, correct?

Also I just tried this and this happened (minor issues):
* it included an old patch as a new patch
* I think the total number of patches included the full tree diff but the full tree diff was missing so there was actually 1 patch less than what the total number of patches suggested.

**Comment by lucasdemarchi** [comment]
> When the baseline changes (in the form 'git pile format-patch OLD_BASELINE..OLD_RESULT_HEAD NEW_BASELINE..NEW_RESULT_HEAD'), git pile doesn't generate a full tree diff, correct?

Correct

> it included an old patch as a new patch

That may happen if the patch was small and got range-diff considered it as a rewrite. Default is if it is more than 60%. I think I forgot to send an additional flag to make that configurable. Was that the case?

> I think the total number of patches included the full tree diff but the full tree diff was missing so there was actually 1 patch less than what the total number of patches suggested.

Oh. I think I need to fix that... Currently it is just using the value from arguments, but if the baseline changed we should override the value from the args. Thanks

**Comment by ashutoshx** [comment]
> That may happen if the patch was small and got range-diff considered it as a rewrite. Default is if it is more than 60%. I think I forgot to send an additional flag to make that configurable. Was that the case?

I think this is issue #29. Yes there may have been large changes to the patch that is probably why it was considered a new patch.
