### ISSUE TITLE
Is this expected 'git pile format-patch --local' behavior?

### ISSUE THREAD

**Issue by ashutoshx** [git-pile/git-pile#48]
I have an extra local pile commit and the corresponding results branch (output of genbranch including the extra pile commit).

When I do a 'git pile format-patch --local' with this, git pile correctly says there are no new changes.

Now I add some patches on top of the results branch. When I again do 'git pile format-patch --local' I only expected to see the patches on top in the cover letter. However, the cover letter is showing all previous changes corresponding to the previous extra pile commit too in the cover letter. Is this expected? Thanks.

**Comment by lucasdemarchi** [comment]
Is it showing the diff or just in the range-diff? For the range-diff it is expected as it's still comparing the new branch with the one in the remote, that doesn't contain your local pile commit. However the diff in the cover should still be valid

**Comment by lucasdemarchi** [comment]
Humn... maybe in this case we should also don't bother with filtering the patch, because it doesn't make much sense.

**Comment by ashutoshx** [comment]
Well I guess the objective of the --local feature is that if someone sends out a cover letter and associated patches which are being reviewed/tested, they can pipeline getting the next cover letter ready (new changes on top of the previous ones). So the second cover letter should have a format which achieves this goal, i.e. one should be able to apply it without changes after the first cover letter is merged. I think the best would be to ignore the remote completely when --local is specified.

**Comment by lucasdemarchi** [comment]
The main intent of the --local flags was to allow someone to update the pile branch with additional local changes regardless of what was already pushed. Example: when applying a patch with `git pile am` and then getting conflicts on genbranch. To update the patch that was applied, one could use the --local flag

**Comment by lucasdemarchi** [comment]
So... I played a little bit (also out of necessity for having 4 pending patch series to even get build working for a feature). Maybe we have to improve the documentation, but if you are using --local, you have to tell git-pile what exactly it needs to compare against. If you do so, then it works as expected and you can maintain several patches on the pile branch, preparing the next ones. Example:

```
git pile am dep1.mbox
git pile genbranch -i
git branch -f dep1  # just to save an easy to remember ref
...
git rebase -i ...
git commit ..
etc
..
git pile format-patch --local dep1...HEAD
```

**Comment by ashutoshx** [comment]
Ah ok, yes, this should work then. As you say maybe needs to be documented but otherwise should work. Though now looking at the man page, this should work even without the --local? Or does --local make a difference? Thanks.

**Comment by lucasdemarchi** [comment]
without --local it complains because the local pile branch contains commits not in the remote. It's usually not what people want to use and was a common source of mistake for people doing a v2 and having the v1 applied locally... In that case the diff sent in v2 was not the entire series, but just the diff v1..v2
