### ISSUE TITLE
Feature request: have git pile format-patch open $EDITOR on 0000-cover-letter.patch

### ISSUE THREAD

**Issue by jnikula** [git-pile/git-pile#63]
I'd find it useful to have `git pile format-patch` automatically run `$EDITOR 0000-cover-letter.patch` at the end. I have something like this in a shell script I use, and it saves me from having to switch to the editor to find the cover letter, and then back to the command line to actually send the patches.

**Comment by lucasdemarchi** [comment]
We try to mimic the options from git-format-patch. Sometimes we get similar options from other commands though (example: the -C mimics that same option from git-commit).

What you're saying would be more or less the equivalent to the --edit option in git-send-email. Would it be ok to be behind a --edit option? We could also add something in the config so people can change the default.
