### ISSUE TITLE
Support .git outside work-tree

### ISSUE THREAD

**Issue by lucasdemarchi** [git-pile/git-pile#65]
Some people prefer to have a bare repo outside and add worktrees on the side. One way to accomplish that is like this in the playground repo:

```
git clone --bare https://github.com/git-pile/playground.git
cd playground.git
git worktree add ../playground internal
```

When we do this we will have the following setup:
```
$ git worktree list
/tmp/playground.git  (bare)
/tmp/playground      b6f49eb [internal]
```

Since git-pile uses the concept of "git_root" or "main checkout", this doesn't work very well since in this scenario there is no such thing: there is the bare repo and each worktree is one storing its data in `playground.git/worktrees`.

**Comment by lucasdemarchi** [comment]
Main alternative that I see is to add an entry to our config, which points to the directory that should be used for worktree. The patches directory (where the pile branch is normally checkout) is relative to that. Then everywhere we use git root we first check the config and fallback to the autodiscover mechanism. This config may be set during `git pile setup` and `git pile init` time.

**Comment by lucasdemarchi** [comment]
Cc @mchehab, since you use such setup. Do you think this would be ok?

**Comment by mchehab** [comment]
Yes, this should work, but it should be noticed that the config file location is different when a bare tree is used.

So, IMO, it would be easier/simpler if git pile would just add an alternative directory to check for the `config` file, e. g.
first check for `.git/config`. If not found, fall back to `./config`.

So, on your example, if git pile is called from `playground.git` (or with `--git-dir=~/playground.git`), the config file will be either `.git/config` or `./config`. If called from a non-bare wortree, the .git file will contain something like this:

```
gitdir: /home/mchehab/playground.git/worktrees/playground
```

And the location of the `config` file will be either:

```
$(cat .git|cut -d' ' -f 2)/../../config
```
or:
```
$(cat .git|cut -d' ' -f 2)/../../.git/config
```

Note: if you want to be extra care, at the fallback case, it could seek at the `config` file for:

```
[core]
	bare = true
```

(although git itself doesn't actually require it)

**Comment by lucasdemarchi** [comment]
@mchehab  but the main issue is to find the working directory, not so much the config. Manually adding some worktrees I have the following:

```
$ git worktree list
/tmp/playground.git          (bare)
/tmp/playground              b6f49eb [internal]
/tmp/playground-tmp-feature  b6f49eb (detached HEAD)
/tmp/playground/patches      a391f37 [pile]
```

If we are in the patches directory, how would git-pile know to go to /tmp/playground? In a non-bare scenario we simply rely on .git (directory) being inside the main checkout.

For the configuration, all out internal uses go through `git config` which already does the right thing depending if  .git is a file or a directory.

Thinking that to support #7 we will have to stop relying on a main worktree anyway.

**Comment by lucasdemarchi** [comment]
If we want the common config, it will always be at `$(git rev-parse --git-common-dir)/config`:

```
/tmp/playground$ git rev-parse --git-common-dir
/tmp/playground.git
/tmp/playground-tmp-feature$ git rev-parse --git-common-dir
/tmp/playground.git
/tmp/playground/patches$ git rev-parse --git-common-dir
/tmp/playground.git
.
```

**Comment by mchehab** [comment]
Ok. Then, 

> If we want the common config, it will always be at `$(git rev-parse --git-common-dir)/config`:
> 
> ```
> /tmp/playground$ git rev-parse --git-common-dir
> /tmp/playground.git
> /tmp/playground-tmp-feature$ git rev-parse --git-common-dir
> /tmp/playground.git
> /tmp/playground/patches$ git rev-parse --git-common-dir
> /tmp/playground.git
> .
> ```

Ok. In this case, setting this on config during `git pile setup` and `git pile init` time should work. It can then use  `$(git rev-parse --git-common-dir)/config` to fill the configuration file with the proper location.

**Comment by lucasdemarchi** [comment]
Another idea: if by convention the patches dir (and hence the checkout) is always inside the worktree we are working with, then we can get away with no configuration. Because we can always calculate the proper worktree we are interested in from the pile.dir configuration. And this would make it compatible with multiple piles as well.  @ashutoshx - do you see this as a possible solution for the issue #7 and this one?
