### ISSUE TITLE
Support multiple piles (per worktree?)

### ISSUE THREAD

**Issue by lucasdemarchi** [git-pile/git-pile#7]
Recent git (I think >= 2.25) supports per-worktree configuration by turning on git config extensions.worktreeConfig true. In order to support multiple piles (think one pile for each branch), it would be a matter of turning this on and have the different configurations per checkout.

If that doesn't work we probably have a bug in git pile. As this is not something we use, we probably do.

**Comment by lucasdemarchi** [comment]
@ashutoshx do you still see value in it?

**Comment by ashutoshx** [comment]
IMO definitely nice to have if/when someone has bandwidth. Yes, multiple worktrees each with its own pile. I could have used this today but it's broken. Though I haven't tried per-worktree configuration, maybe I should try that sometime and see if it works. Thanks.
